1.Write a NumPy program to create a 3x3x3 array filled with arbitrary values

In [11]:
import numpy as n
a=n.random.random((3,3,3))
print(a)

[[[0.10237207 0.37353017 0.1258236 ]
  [0.85506035 0.95630757 0.86740443]
  [0.13832858 0.22192031 0.62728214]]

 [[0.6499242  0.70867516 0.50322228]
  [0.7889774  0.38252532 0.82919947]
  [0.93845229 0.36983855 0.93187035]]

 [[0.2588756  0.37745452 0.25293185]
  [0.06679771 0.51462781 0.84137903]
  [0.57054846 0.87500446 0.15745657]]]


2.Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.

In [3]:
import numpy as n
b=n.arange(16,55)
print(b)

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


3.Write a NumPy program to multiply two given arrays of the 2 x 3 size element-by-element. 

In [4]:
import numpy as n
c=n.array([[10,2,5],[2,4,6]])
d=n.array([[3,9,7],[1,4,8]])
e=c*d
print(e)

[[30 18 35]
 [ 2 16 48]]


4.Write a NumPy program to create a 3X4 array and iterate over it

In [9]:
import numpy as n
k=n.array([[12,11,10,9],[8,7,6,5],[4,3,2,1]])
for i in k:
    for j in i:
        print(j)

12
11
10
9
8
7
6
5
4
3
2
1


5.Write a NumPy program to compute the sum of the diagonal element(Trace of array) of a given array(4x4). (use built in linear algebra function only) 

In [10]:
import numpy as n
k=n.array([[1,2,3,4],[5,6,7,8],[9,0,10,11],[12,13,14,15]])
dsum=n.trace(k)
print(dsum)

32


#### NOTE : 
Submit the notebook file with name : 2kxx-CSE-xx_your name

questions containing "given array" declare the array and give appropriate values 