## What is NumPy?

NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
NumPy stands for Numerical Python.

## Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
Arrays are very frequently used in data science, where speed and resources are very important.

In [1]:
list1 = ["apple", "banana", "cherry"]
print(list1)

['apple', 'banana', 'cherry']


In [7]:
list2 = [1, 5, 7, 9, 3]
print(list2)

[1, 5, 7, 9, 3]


In [6]:
list3 = [True, False, False]
print(list3)

[True, False, False]


In [5]:
list4 = ["abc", 34, True, 40, "male"]
print(list4)

['abc', 34, True, 40, 'male']


### Import NumPy

In [11]:
import numpy as np

### Dimensions in Arrays

In [12]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2d)

[[1 2 3]
 [4 5 6]]


In [5]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Access Array Elements (INDEXING)

In [8]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1])

2


In [9]:
print(arr[2] + arr[3])

7


In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd row 2nd element : ', arr[1, 1])

1st row 2nd element :  7


In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

### Negative Indexing

In [13]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -2])

Last element from 2nd dim:  9


### NumPy Array Slicing

Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [18]:
arr = np.array([5, 1, 6, 8, 4, 3, 7, 9])

print(arr[1:5])

[1 6 8 4]


In [19]:
print(arr[4:])

[4 3 7 9]


In [20]:
print(arr[:4])

[5 1 6 8]


In [26]:
print(arr[1:7:3])

[1 4]


### Data Types in Python


By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABC- D"

integer - used to represent integer numbers. e.g. -1, -2,-  -3

float - used to represent real numbers. e.g. 1.2, 4- 2.42

boolean - used to represent True or F- alse.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 - + 2.5j

Data Types i- n NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

In [22]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [23]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


### Iterating Arrays

In [24]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


 ### Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [28]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


### Sorting Arrays

In [34]:
arr = np.array([3, 2, 5, 1, 6, 8, 4, 3, 7, 0, 1])
arr2 = np.array([[10, 82, -3], [41, 54, 6]])
print(np.sort(arr))
print(np.sort(arr2))

[0 1 1 2 3 3 4 5 6 7 8]
[[-3 10 82]
 [ 6 41 54]]


### Using array-generating functions

In [ ]:
For larger arrays it is inpractical to initialize the data manually, using explicit python lists. 
Instead we can use one of the many functions in `numpy` that generate arrays of different forms. 
Some of the more common are:

#### random data

In [1]:
from numpy import random

In [48]:
# uniform random numbers in [0,1]
np.random.rand(6,5)

array([[0.20508737, 0.81009856, 0.58962226, 0.52074126, 0.98156317],
       [0.14759114, 0.22895729, 0.09834005, 0.76680891, 0.06806618],
       [0.9086079 , 0.39435201, 0.5471645 , 0.44614344, 0.7735703 ],
       [0.64452178, 0.62754733, 0.71546549, 0.22504517, 0.79063897],
       [0.85483575, 0.65424449, 0.1126431 , 0.54948272, 0.33836758],
       [0.07398044, 0.16013431, 0.37219235, 0.12968537, 0.46513469]])

In [55]:
np.random.randint(20,size=(5))

array([ 1,  8,  5,  8, 17])

## Linear algebra

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [56]:
v1 = np.arange(0, 5, 1)
print(v1)

[0 1 2 3 4]


In [57]:
v1 * 2

array([0, 2, 4, 6, 8])

In [58]:
v1 + 2

array([2, 3, 4, 5, 6])

In [59]:
A = np.array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])
A * 2, A + 2

(array([[ 0,  2,  4,  6,  8],
        [20, 22, 24, 26, 28],
        [40, 42, 44, 46, 48],
        [60, 62, 64, 66, 68],
        [80, 82, 84, 86, 88]]),
 array([[ 2,  3,  4,  5,  6],
        [12, 13, 14, 15, 16],
        [22, 23, 24, 25, 26],
        [32, 33, 34, 35, 36],
        [42, 43, 44, 45, 46]]))

### Element-wise array-array operations

In [60]:
print(A)
A * A # element-wise multiplication

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [61]:
A.shape, v1.shape

((5, 5), (5,))

In [62]:
print(A)
print(v1)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[0 1 2 3 4]


In [63]:
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

### Matrix algebra

What about matrix mutiplication? There are two ways. We can either use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [74]:
print(A)
np.dot(A, A)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [26]:
print(A)
print(v1)
np.dot(v1,A)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[0 1 2 3 4]


array([300, 310, 320, 330, 340])

### Array/Matrix transformations

In [33]:
from numpy import matrix

In [68]:
print(v1)
v = np.matrix(v1).T
print(v)

[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [70]:
complex = [[5+1j, 2-2j], [6+3j, 5+4j]]
C = np.matrix(complex)
C

matrix([[5.+1.j, 2.-2.j],
        [6.+3.j, 5.+4.j]])

In [71]:
np.conjugate(C)

matrix([[5.-1.j, 2.+2.j],
        [6.-3.j, 5.-4.j]])

We can extract the real and imaginary parts of complex-valued arrays using `real` and `imag`:

In [72]:
np.real(C)

matrix([[5., 2.],
        [6., 5.]])

In [73]:
np.imag(C) 

matrix([[ 1., -2.],
        [ 3.,  4.]])

### Matrix computations

#### Inverse

In [49]:
abs(C)

matrix([[5.09901951, 2.82842712],
        [6.70820393, 6.40312424]])

In [54]:
print(C)
np.linalg.inv(C) # equivalent to C.I 

[[5.+1.j 2.-2.j]
 [6.+3.j 5.+4.j]]


matrix([[ 0.14329897-0.14742268j,  0.05773196+0.07010309j],
        [-0.11443299+0.18247423j,  0.04742268-0.15670103j]])

In [75]:
np.linalg.det(A)

0.0