In [1]:
'''NumPy array is 50 times faster than python lists.
Created in 2005 by Travis Oliphant. NumPy stands for Numerical Python.
array object is called ndarray'''

'NumPy array is 50 times faster than python lists.\nCreated in 2005 by Travis Oliphant. NumPy stands for Numerical Python.\narray object is called ndarray'

In [6]:
list1=['Apple','Samsung','OnePlus']
print(list1)
list2=[1,2,3,4,5]
print(list2)
list3=[True,False,True]
print(list3)
list4=[1,'Ayooo',False,16]
print(list4)

['Apple', 'Samsung', 'OnePlus']
[1, 2, 3, 4, 5]
[True, False, True]
[1, 'Ayooo', False, 16]


In [7]:
import numpy as np

In [11]:
#difference between array and list
arr=np.array([1,2,3,4,5])
print(arr)
list2=[1,2,3,4,5]
print(list2)
print(type(arr))
print(type(list2))

[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
<class 'list'>


In [18]:
#multidimensional array
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d)
arr3d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3d)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
ar=np.array(9)
arr=np.array([1,2,3,4,5])
arr2d=np.array([[1,2,3],[4,5,6]])
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(ar.ndim)
print(arr.ndim)
print(arr2d.ndim)
print(arr3d.ndim)

0
1
2
3


In [30]:
arr=np.array([1,2,3,4,5])
print(arr[1])
print(arr[0]+arr[2]+arr[4])
print(arr+arr[2]+arr[4])
arr2d=np.array([[1,2,3],[4,5,6]])
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr2d[1,1])
print(arr3d[1,1,1])
print(arr2d[0,-1])
print(arr3d[1,-2,-1])

2
9
[ 9 10 11 12 13]
5
11
3
9


In [37]:
arr=np.array([1,2,3,4,5])
arr2d=np.array([[1,2,3],[4,5,6]])
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1:])
print(arr[1:3:1])
print(arr[1:3])
print(arr[:3])

[2 3 4 5]
[2 3]
[2 3]
[1 2 3]


In [39]:
arr=np.array([1,2,3,4,5])
arrA=np.array(['Apple','Samsung','OnePlus'])
print(arr.dtype)
print(arrA.dtype)

int32
<U7


In [42]:
arr=np.array([1,2,3,4,5])
for i in arr:
    print(i)
print('\n')
arr2d=np.array([[1,2,3],[4,5,6]])
for j in arr2d:
    for k in j:
        print(k)

1
2
3
4
5


1
2
3
4
5
6


In [46]:
arr=np.array([1,2,3,4,5])
x=np.where(arr==4)
print(x)
arr1=np.array([1,2,9,4,5,9,4 ,2,4,9])
y=np.where(arr1==9)
print(y)

(array([3], dtype=int64),)
(array([2, 5, 9], dtype=int64),)


In [48]:
arr1=np.array([1,2,9,4,5,9,4 ,2,4,9])
print(np.sort(arr1))
arr2=np.array([[13,2,46],[34,6,27]])
print(np.sort(arr2))

[1 2 2 4 4 4 5 9 9 9]
[[ 2 13 46]
 [ 6 27 34]]


In [49]:
from numpy import random

In [123]:
#creating a matrix with random decimal values between [0,1] with order m*n
x=np.random.rand(3,4)
y=np.random.randint(1,6)
z=np.random.randint(20,size=5)
print(x)
print(y)
print(z)

[[0.17137904 0.67963579 0.93090528 0.14683605]
 [0.1734718  0.38775097 0.55359684 0.51912006]
 [0.80391705 0.05370944 0.76434355 0.42896275]]
1
[19  1  9  8  6]


In [128]:
v1=np.arange(0,5,1)
print(v1)
print(v1*2)
print(v1-2)
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d*2,arr3d+2
arr3d*arr3d

[0 1 2 3 4]
[0 2 4 6 8]
[-2 -1  0  1  2]


array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[ 49,  64,  81],
        [100, 121, 144]]])

In [133]:
v1.shape,arr3d.shape
arr3d=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.dot(arr3d,arr3d)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [136]:
from numpy import matrix

In [138]:
v=np.matrix(v1).T
print(v)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [164]:
complex=[[1+1j,2-5j],[4-1j,-6j]]
C=np.matrix(complex)
C

matrix([[ 1.+1.j,  2.-5.j],
        [ 4.-1.j, -0.-6.j]])

In [165]:
np.conjugate(C)

matrix([[ 1.-1.j,  2.+5.j],
        [ 4.+1.j, -0.+6.j]])

In [166]:
np.real(C)

matrix([[ 1.,  2.],
        [ 4., -0.]])

In [168]:
np.imag(C)

matrix([[ 1., -5.],
        [-1., -6.]])

In [169]:
abs(C)

matrix([[1.41421356, 5.38516481],
        [4.12310563, 6.        ]])

In [170]:
np.linalg.inv(C)

matrix([[-0.36226415-0.06792453j,  0.27924528+0.17735849j],
        [ 0.01509434+0.25283019j,  0.07169811-0.0490566j ]])

In [171]:
np.linalg.det(C)

(2.9999999999999996+16j)

In [134]:
!pip install pandas

In [135]:
import pandas as pd

In [173]:
np.arange(0,20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [175]:
df=pd.DataFrame(np.arange(0,20).reshape(4,5),index=["Row1","Row2","Row3","Row4"],columns=["Col1","Col2","Col3","Col4","Col5"])

Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row2     5     6     7     8     9
Row3    10    11    12    13    14
Row4    15    16    17    18    19

In [176]:
df.head()

Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row2     5     6     7     8     9
Row3    10    11    12    13    14
Row4    15    16    17    18    19

In [177]:
df.tail()

Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row2     5     6     7     8     9
Row3    10    11    12    13    14
Row4    15    16    17    18    19

In [178]:
type(df)

pandas.core.frame.DataFrame

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row1 to Row4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    4 non-null      int32
 1   Col2    4 non-null      int32
 2   Col3    4 non-null      int32
 3   Col4    4 non-null      int32
 4   Col5    4 non-null      int32
dtypes: int32(5)
memory usage: 112.0+ bytes


In [180]:
df.describe()

Col1       Col2       Col3       Col4       Col5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    7.500000   8.500000   9.500000  10.500000  11.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     3.750000   4.750000   5.750000   6.750000   7.750000
50%     7.500000   8.500000   9.500000  10.500000  11.500000
75%    11.250000  12.250000  13.250000  14.250000  15.250000
max    15.000000  16.000000  17.000000  18.000000  19.000000

In [181]:
type(df["Col1"])

pandas.core.series.Series

In [182]:
df[['Col1','Col2','Col3']]

Col1  Col2  Col3
Row1     0     1     2
Row2     5     6     7
Row3    10    11    12
Row4    15    16    17

In [194]:
df.loc[['Row3','Row4']]

Col1  Col2  Col3  Col4  Col5
Row3    10    11    12    13    14
Row4    15    16    17    18    19

In [195]:
df.iloc[2:4,0:2]

Col1  Col2
Row3    10    11
Row4    15    16